[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/pages/gallery.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/pages/404.html"
  status = 404
