name: CI pipeline to run lint checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '10.7.0'

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run prettier

    - name: Run HTMLHint
      run: npm run htmlhint

    - name: Run Stylelint
      run: npm run stylelint
